### ISSUE TITLE
How do you exit the terminal program?

### ISSUE THREAD

**Issue by DePingus** [oakes/ansiwave#6]
The usual suspects (ctrl+q, ctrl+x) don't seem to work. Sometimes ctrl+c works, sometimes it doesn't. Instead it changes "copy with ctrl k" into "now you can paste in the editor with ctrl l" for whatever item is highlighted.

**Comment by oakes** [comment]
Which OS are you running on?

**Comment by oakes** [comment]
If you're using windows, try 1.2.2 which i just released. There was a problem with the way it shutdown that prevented it from restoring the terminal so it looked like it didn't shut down. But maybe your issue is different because if it showed the "now you can paste..." message after ctrl+c, then that must mean it didn't actually shut down. Weird.

**Comment by DePingus** [comment]
I'm on linux using v1.1.0 of the ansiwave client. I can't reproduce it. It happened like 4 of the 10 times I opened the program the other day. If I can reproduce I'll open a new issue. Thanks for looking.

Happy New Year!
