### ISSUE TITLE
Mouse scrolling in terminal

### ISSUE THREAD

**Issue by PfisterFactor** [oakes/ansiwave#8]
I love the terminal client! I think a useful feature to implement though is mouse scrolling for navigation within the terminal, it is a bit tedious to navigate with just the keyboard.

If you can point me in the right direction I can try and implement a pull request for it. I have no experience with nim though so bear with me 😅.

**Comment by oakes** [comment]
Yeah i've been meaning to do that, and you motivated me to finally add it :D See this commit: https://github.com/ansiwave/ansiwave/commit/8ea9f5d24aa05c965566c51f9da7d0092798eeb3 If you notice any problems with it, let me know (you need to build with `nimble build -d:release` because it's pretty slow when not in release mode).

**Comment by PfisterFactor** [comment]
Nice! Thanks for the quick turnaround!

**Comment by oakes** [comment]
Just released 1.3.4 with this feature included
